version: '3.9' # optional since v1.27.0
services:
    app:
        build: .
        ports:
            - '8080:8080'
        depends_on:
            - redis
        # links:
        #   - redis
    redis:
        image: redis
        ports:
            - '6379:6379'
